name = "Void Atlas"
author = "m9ple"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa353acd650a8716265be6766637a61d548828dce7ae26d7b388b142ebec21bc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
