name = "Void Atlas"
author = "m9ple"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d98fc4d562669ad451f301d6fce7243770fa51eda90fc0c3616f259b44fd817"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
