<?php
/*
   Mod Manager v15 Mod log display handler
      Written by Ken Roy, TNG Test Manager
      v12 Updated by Ken Roy and Robin Richmond
      v13 Updated by Rick Bisbee
      * Updates code/styling for new TNGv13 Admin pages no longer using iframes.
      * No changes to core (OOP classes) functionality from TNGv12.

    Note: this code deals with three types of log entries:

    1. The newest, GENIII log entries that consist of one physical line that contains multiple HTML lines. The first line is pipe-delimited and contains the log entry heading.

    2. Older (probably generated by test versions of GenIII -- not sure) log entries that also consist of one physical line that contains multiple HTML lines.  The first line is not pipe-delimited, but it does contains a log entry heading.

    3. Even older log entries that consist of multiple physical lines, in reverse chronological order.  Thus, the first line we encounter is the last line of the log entry.  But we use that last line as the entry header.

    --Robin Richmond

*/
require 'begin.php';
require 'adminlib.php';
$textpart = "mods";

require_once $mylanguage . '/admintext.php';

$admin_login = 1;
require 'checklogin.php';
require 'version.php';

include 'classes/mmtabs.inc';

// prevent direct URL access to Mod Manager if not the TNG Administrator
if ($assignedtree || !$allow_edit) {
	$message = $admtext['norights'];
	header("Location: admin_login.php?message=" . urlencode($message));
	exit;
}

define('YES', "1");
define('NO', "0");

if (!isset($sub)) $sub = "tables";

/***************************************************************
    1. OUTPUT STD ADMIN PAGE HTML HEADER + ADDITIONS
 ***************************************************************/
$flags['modmgr'] = true;
tng_adminheader($admtext['showlogfile'], $flags);

require $subroot . 'mmconfig.php';

if (!isset($options['show_analyzer'])) $options['show_analyzer'] = "0";
if (!isset($options['show_developer'])) $options['show_developer'] = "0";
if (!isset($options['show_updates'])) $options['show_updates'] = "0";

$min_width = $sitever == 'mobile' ? '0' : '640px';

/* Adjust positioning for problem templates */
switch ($templatenum) {
	case 7:
		$margin_top = "0px";
		break;
	default:
		$margin_top = "162px";
		break;
}

if ($options['compress_log'] == YES) {
	echo "
<style>
	.collapse {
    background: url(img/tng_collapse.gif) no-repeat left center;
  }
	.collapse a {
    text-decoration: none;
  }
	.moddetails {display:none;}
</style>
";
	$hideDetails = "style=\"display:none;\"";
} else {
	$hideDetails = "";
}

/* Height of the table display must be set for
** each page to account for differences in
** heading heights.
**
** The <head> tag must be explicitly closed. */
echo "
<style>
  .tableFixedHead {
    height:calc( 100vh - 220px ) !important;
  }
</style>
</head>
";

/***************************************************************
    2. OUTPUT TNG ADMIN TOP BANNER AND LEFT SIDE MENUS
 ***************************************************************/
echo tng_adminlayout();

/***************************************************************
    3. PREPARE MOD MANAGER PAGE TITLE, TABS AND HORZ MENU
 ***************************************************************/
$parts = explode(".", $tng_version);
//$tngmodver = "Mods for TNG v{$parts[0]}";
$modtabs = set_horizontal_tabs($options['show_analyzer'], $options['show_developer'], $options['show_updates']);

$innermenu = set_innermenu_links($tng_version);
$menu = doMenu($modtabs, "viewlog", $innermenu);

if (!isset($message)) $message = "";
echo displayHeadline($admtext['modmgr'], "img/modmgr_icon.gif", $menu, $message);

$logheader =  $admtext['recentactions'];
$first_menu = TRUE;

$clearmmlog = empty($_GET['clearmmlog']) ? false : true;

/***************************************************************
    4. MOD MANAGER LOG DISPLAY PAGE CONTENT
 ***************************************************************/
$logfilename = 'modmgrlog.txt';
if (!isset($options['modlogfile'])) $options['modlogfile'] = $logfilename;

if ($clearmmlog || !file_exists($options['modlogfile'])) {
	$content = "#### Mod Manager Log created " . date("D d M Y h:i:s A", time() + (3600 * $time_offset)) . " ####";
	file_put_contents($options['modlogfile'], $content);
}
$nColumns = 1;

echo "
<div class='admin-main'>
  <div class='tableFixedHead roundtop'>
  <table id=\"mmtable\" class=\"mmtable\">
    <thead>
      <tr>
        <th class='fieldnameback fieldname'>
          Mod Manager Most Recent Actions
        </th>
      </tr>
    </thead>
    ";
$lines = file($options['modlogfile']);
if ($lines) {
	$actionCount = 0; // Counts the actions, i.e. the "log entries"
	$logEntryDetails = "";
	// These two boolean variables are used (a) to flag that the first line of a log entry
	// has been output, and (b) to distinguish between newer and older log entries, because
	// the detail lines of old log entries are in reverse chronological order.
	$type1Or2EntryIsActive = false;
	$type3EntryIsActive = false;
	foreach ($lines as $line) {
		//Because there are multiple tests involved, we use this boolean variable as we
		//determine if the log entry is in the newer one-physical-line format.
		$newLogFormat = false;
		//Log entries have to start with a date.  This test is necessary because some old log entries
		//contain
		if (preg_match("/^\w{3} \d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2} \w{2}/i", $line, $matches)) {
			//New log entries have a <br /> more than 20 characters from the end,
			//and less than 150 characters from the beginning
			$br = strpos($line, "<br />");
			if ($br !== false) {
				if (strlen($line) - $br > 20 || $br < 150) $newLogFormat = true;
			}
		}

		if ($newLogFormat) {
			//This is a one-physical-line log entry.
			if ($logEntryDetails) {
				echo "<tr class=\"databack moddetails\" $hideDetails id=\"data$actionCount\"><td colspan=\"$nColumns\"class='mmpanel'>$logEntryDetails</td></tr>\n";
				$type3EntryIsActive = false;
			}
			$actionCount++;
			//Suppress any <hr> elements in the first line of the log entry.
			$heading = str_replace("<hr />", "", substr($line, 0, $br));
			//The rest of the log entry goes into the details.
			$logEntryDetails = substr($line, $br + 6);
			$type1Or2EntryIsActive = true;

			// break out the status from $heading, set $dynoclass and add below
			if (false !== strpos($heading, "errors")) {
				$dynoclass = "msgerror";
			} elseif (false !== stripos($heading, "Clean Up")) {
				$dynoclass = "partinst";
			} elseif (false !== stripos($heading, "modrem")) {
				$dynoclass = "ready";
			} elseif (false !== stripos($heading, "installed")) {
				$dynoclass = "installed";
			} elseif (false !== stripos($heading, "updated")) {
				$dynoclass = "installed";
			} elseif (false !== stripos($heading, "filedel")) {
				$dynoclass = "";
			} else {
				$dynoclass = "lightback";
			}
			echo "<tr class='$dynoclass'>";
			echo "<td class=\"mmrounded action $dynoclass\" id=\"action$actionCount\">$actionCount. $heading</td></tr>\n";
		} else {
			// This isn't a one-physical-line log entry.  But we also need to look for old log
			// entries that consist of multiple physical lines.
			//This pattern should match old "type 3" log entries.
			//(I know that it isn't perfect, but it's the best I could come up with.)
			$match = preg_match("/^(\w{3} \d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2} \w{2}) ([.\w_-]*)\.cfg(.*)\(([\w: ]*)\)/i", $line, $matches);
			if ($match) {
				//It looks like this is the beginning of an old multiple-physical-line log entry.
				if ($logEntryDetails) {
					echo "<tr class=\"databack moddetails\" $hideDetails id=\"data$actionCount\"><td colspan=\"$nColumns\">$logEntryDetails</td></tr>\n";
					$type1Or2EntryIsActive = false;
					$logEntryDetails = "";
				}
				$actionCount++;
				$modFilename = $matches[2]; //I'm not using this variable now, but hope to later.
				echo "<tr class=\"databack\">";
				echo "<td class=\"action\" id=\"action$actionCount\">$actionCount. $line</td></tr>";
				$type3EntryIsActive = true;
			} else {
				//Couldn't parse the alternate pattern - treat this as an unrecognizable entry
				if ($type3EntryIsActive) {
					//Add the unrecognized entry at the beginning of existing details
					$logEntryDetails = "$line</span><br />\n$logEntryDetails"; //add </span> to close a chronically unclosed span in the log.
				} else if ($type1Or2EntryIsActive) {
					//Add the unrecognized entry at the end of the existing details
					$logEntryDetails .= "<br />$line";
				} else {
					//There's no outstanding log entry to add this to. Just display it without any compression controls
					echo "<tr><td class=\"databack\" colspan=\"$nColumns\"><b>?? </b>$line</td></tr>\n";
				}
			}
		}
	}
}
// Are any details left over from the very last log entry?
if ($logEntryDetails) {
	echo "<tr class=\"databack moddetails\" $hideDetails id=\"data$actionCount\"><td colspan=\"$nColumns\">$logEntryDetails</td></tr>\n";
}

echo "
	</table>
  </div><!--tableFixedHead-->
	<br />
</div><!-- admin-main-->";
/*************************************************************************
FUNCTIONS
 *************************************************************************/
function set_innermenu_links(string $tng_version, string $pageID = 'viewlog'): string
{
	global $text, $admtext;
	$parts = explode(".", $tng_version);		// added to determine TNG vNN for
	$tngmodver = "{$admtext['tngmods']} v{$parts[0]}";	// Mods for TNG vNN text display
	$tngmodurl = "Mods_for_TNG_v{$parts[0]}";	// Mods for TNG vNN URL
	$helplang = findhelp("modhandler_help.php");

	// inner menu help
	$innermenu = "<a href=\"#\" onclick=\"return openHelp('$helplang/modhandler_help.php#$pageID');\" class=\"lightlink\">{$admtext['help']}</a>
";

	// expand & collapse all
	$innermenu .= " &nbsp;|&nbsp; <a href=\"#\" class=\"lightlink\" id=\"expandall\"> {$text['expandall']}</a>
";
	$innermenu .= " &nbsp;|&nbsp; <a href=\"#\" class=\"lightlink\" id=\"collapseall\">{$text['collapseall']}</a>
";

	//This section for View Log only to allow clearing the log
	$innermenu .= " &nbsp;|&nbsp; <a href=\"admin_showmodslog.php?clearmmlog=true\" onclick=\"return confirm( '{$admtext['confirmclearlog']}')\" class=\"lightlink\">{$admtext['clearlog']}</a>
";

	// MM syntax
	$innermenu .= "&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"https://tng.lythgoes.net/wiki/index.php?title=Mod_Manager_Syntax\" target=\"_blank\" class=\"lightlink\">{$admtext['modsyntax']}</a>
";

	// mod guidelines
	$innermenu .= "&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"https://tng.lythgoes.net/wiki/index.php?title=Mod_Guidelines\" target=\"_blank\" class=\"lightlink\">{$admtext['modguidelines']}</a>
";

	// mods for TNGv10
	$innermenu .= "&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"https://tng.lythgoes.net/wiki/index.php?title=Category:$tngmodurl\" target=\"_blank\" class=\"lightlink\">$tngmodver</a>
";
	return $innermenu;
}
/*************************************************************************
JQUERY/JAVASCRIPT FUNCTIONS
 *************************************************************************/
?>
<script>
	//qQeury document ready handler and embedded event handlers added by RR
	jQuery(document).ready(function() {
		//Handler for the triangular arrow icon on the first line of each log entry.
		jQuery('.action').click(function() {
			var myId = jQuery(this).attr("id"); //Get the log entry number
			var dataId = myId.replace("action", "data"); //Generate the ID of the mod details
			if (jQuery(this).hasClass("collapse")) {
				//The details are collapsed...no...hmmm... it works right, but I must be using the wrong label for the "collapse" class..
				jQuery('#' + dataId).hide();
				jQuery(this).removeClass("collapse");
			} else {
				jQuery(this).addClass("collapse");
				jQuery('#' + dataId).show();
			}
		});

		//Handler for the "open all" text link
		jQuery('#expandall').click(function(event) {
			//jQuery(this).attr("src","img/tng_collapseall.png");
			jQuery(".action").addClass("collapse");
			jQuery(".moddetails").show();
			event.preventDefault();
		});

		//Handler for the "close all" text link
		jQuery('#collapseall').click(function(event) {
			//jQuery(this).attr("src","img/tng_expandall.png");
			jQuery(".action").removeClass("collapse");
			jQuery(".moddetails").hide();
			event.preventDefault();
		});
	});
</script>
<?php
echo tng_adminfooter();
