name: tng

services:
# HTML & PHP server for the web GUI + logic
  htmlserver:
    build:
      context: .
    container_name: tng_server
    env_file:
      - .env
    ports:
      - ${TNG_HTML_PORT}:80
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ${TNG_HTML_DIR}
        target: /var/www/html
    depends_on:
      - database

# MySQL database
  database:
    image: docker.io/mysql:9.3.0
    container_name: tng_db
    env_file:
      - .env
    ports:
      - ${DB_EXT_PORT}:3306
    environment:
      # Edit these in the .env file
      - MYSQL_DATABASE: ${DB_TITLE}
      - MYSQL_USER: ${DB_USERNAME}
      - MYSQL_PASSWORD: ${DB_PASSWORD}
        # - MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ${DB_DATA_LOCATION}
        target: /var/lib/mysql
    restart: always

# GUI for direct administration of the database, when necessary.
  phpmyadmin:
    image: docker.io/phpmyadmin:5.2.2-apache
    container_name: tng_phpmyadmin
    env_file:
      - .env
    environment:
      - PMA_HOST: database
      - PMA_PORT: ${DB_EXT_PORT}
      - PMA_USER: ${PHPMYADMIN_USERNAME}
      - PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    depends_on:
      - database

volumes:
  database:
  tnghtml:
