name = "Aelwyd"
author = "m9ple"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e8a5760d64dbab7f8eacdb72aad4b9e980eb50c0719b98cf714f98b4975c284"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
