name = "Void Atlas 1.3.2"
author = "m9ple"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faa57af38215f058a6fd429079080aeb91b4d32c4ff2bf852eb6ff51cb31639d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
