name = "Void Atlas 1.3.2"
author = "m9ple"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c04ab722badc6a9b7c9a6da9cead42119be525cb9c83fcae93b25fc14fd54f4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
