name = "Aelwyd"
author = "m9ple"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6523fd50e1afcd53fd781d4cb055266046a5434b46ad4987dbff67d2d922bce2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
